### ISSUE TITLE
When things get stuck as you try to pull them around a corner, you can't move ~at all@

### ISSUE THREAD

**Issue by sohpeach** [ninjanomnom/tgstation#105]
![image](https://user-images.githubusercontent.com/1499676/71861407-32272f80-30ee-11ea-9e16-e5df0a86a3a3.png)
In this case I am dragging the closet. I moved far enough north that I couldn't move further, but it stops me from moving in any direction.

**Comment by ninjanomnom** [comment]
This is intentional

**Comment by sohpeach** [comment]
It's intentional to not be able to move back towards the object?

**Comment by ninjanomnom** [comment]
Oh in any direction, yeah that's a minor issue to resolve
