### ISSUE TITLE
Bloody footprints are somewhat inconsistent

### ISSUE THREAD

**Issue by MMMiracles** [ninjanomnom/tgstation#110]
![image](https://user-images.githubusercontent.com/9276171/71862060-89b1a500-30c6-11ea-9bae-275c35ac2983.png)

Footprints seem to sporadically have gaps between them with walking, this was the most consistent I got it to create gaps. Couldn't recreate past attempting multiple times to get the result.

**Comment by Couls** [comment]
steps to reproduce? pun intended
