### ISSUE TITLE
A long list of test server bugs.

### ISSUE THREAD

**Issue by ArcaneMusic** [ninjanomnom/tgstation#117]
## Testmerges: All of it.

Issues:
Catching thrown objects results in a Qdel, for some reason.
Single pane windows seem to allow you to phase them them at will, appears to be the same thing with all single pane objects (railings, windows, Rwindows, etc.)
Single Pane objects like those above are able to have multiple placed on the same turf.
Objects with boomerang behavior seem to interact oddly, as they'll only return when they hit a target, unlike usual.
Plants within botany, when harvest, shotgun their plant products on turfs all around the harvester, with little order.
![image](https://user-images.githubusercontent.com/41715314/87998548-3f25d200-cac6-11ea-892a-fd1744757c0e.png)

**Comment by Couls** [comment]
All of these have since been fixed on my local branch, your help was very appreciated!
