### ISSUE TITLE
Pixel projectiles dont use pixel movement

### ISSUE THREAD

**Issue by ninjanomnom** [ninjanomnom/tgstation#12]

**Comment by Couls** [comment]
projectiles might not need p_x or p_y anymore haha nevermind but you can use p_x and p_y for a more accurate target

**Comment by Couls** [comment]
pixel projectiles have been converted over but they can definitely use a lot more love, the current implementation is pretty basic

**Comment by ninjanomnom** [comment]
It's fine for now probably
