### ISSUE TITLE
orange does not work with pixel movement, may happen with other range procs as well

### ISSUE THREAD

**Issue by Couls** [ninjanomnom/tgstation#75]
Description for the orange proc: This instruction is identical to oview() except visibility is ignored. All objects are included in the list whether they are visible or not. The center object and its contents are excluded.
when orange is taken from a turf all contents of the turf can still be considered if they're actually on multiple tiles, this breaks process_spacemove because it looks for movables in the turf to push off of and then takes itself.

easy way to reproduce is to go into space and call the "get_spacemove_backup" proc on the mob in space and it'll return the mob it was called on

**Comment by ninjanomnom** [comment]
This doesn't sound like an issue with orange and I'm glad it acts like that as it makes more sense. This is more just an issue with most of our code assuming things only exist on one tile.

**Comment by Couls** [comment]
Just documenting it so we know what to look for in similar situations
