### ISSUE TITLE
Beams aren't lined up in pixel movement

### ISSUE THREAD

**Issue by Couls** [ninjanomnom/tgstation#80]
This is a complex one, medbeam and changeling tentacle still used turfs to draw its line and probably need a complete rewrite for pixel movement

**Comment by tralezab** [comment]
assumingly this is easy, right?

![image](https://user-images.githubusercontent.com/40974010/70273562-2b0fa900-175f-11ea-97c7-2aaca8eae2b6.png)

**Comment by Couls** [comment]
I tried that and it still looked very off because the segments didn't line up, give it a shot
